#!/bin/bash

# Script to help verify GitHub secrets are set up
# This won't show the secret values, but helps you check if they exist

echo "🔐 GitHub Secrets Verification Guide"
echo "===================================="
echo ""
echo "This script provides instructions to verify your GitHub secrets."
echo ""
echo "📋 Required Secrets:"
echo ""
echo "1. FIREBASE_SERVICE_ACCOUNT_KIDS_IN_MOTION_WEBSITE_B1C09"
echo "   Purpose: Deploy to Firebase Hosting"
echo "   Format: JSON service account key"
echo ""
echo "2. GCP_SA_KEY"
echo "   Purpose: Deploy backend to Cloud Run"
echo "   Format: JSON service account key"
echo ""
echo "🔍 How to Check:"
echo ""
echo "1. Open your browser and go to:"
echo "   https://github.com/dannygardner26/kidsinmotion-website/settings/secrets/actions"
echo ""
echo "2. You should see both secrets listed"
echo ""
echo "3. If secrets are missing, follow these steps:"
echo ""
echo "   For FIREBASE_SERVICE_ACCOUNT_KIDS_IN_MOTION_WEBSITE_B1C09:"
echo "   a) Go to: https://console.firebase.google.com"
echo "   b) Select project: kids-in-motion-website-b1c09"
echo "   c) Settings → Service Accounts → Generate New Private Key"
echo "   d) Download JSON and paste entire contents as secret"
echo ""
echo "   For GCP_SA_KEY:"
echo "   a) Go to: https://console.cloud.google.com/iam-admin/serviceaccounts"
echo "   b) Select or create service account with these roles:"
echo "      - Cloud Build Editor"
echo "      - Cloud Run Admin"
echo "      - Service Account User"
echo "   c) Keys tab → Add Key → Create New Key → JSON"
echo "   d) Download JSON and paste entire contents as secret"
echo ""
echo "✅ Once secrets are added, test deployment:"
echo "   https://github.com/dannygardner26/kidsinmotion-website/actions"
echo ""
